name: temppython

channels:
    - pytorch
    - conda-forge

dependencies:
    - python=3.10
    - pip
    - numpy
    - scipy
    - scikit-image
    - matplotlib
    - openjdk==17.0.9
    - pytorch
    - h5py
    - dask
    - pydicom
    - pytest
    - pre-commit
    - coverage
    - ipykernel
    - networkx==3.1
    - pip:
        - python-bioformats
        - python-javabridge
        - protobuf==3.20.3
        - deepcell==0.12.7
        - onnx==1.14.0
        - onnxruntime==1.15.1
        - opencv-contrib-python
        - openslide-python
        - scanpy
        - anndata
        - tqdm
        - loguru
        - pandas
        - torch-geometric==2.3.1
        - JPype1==1.4.1
        - torchvision==0.14.1
        - spams

