name: newtemppython

channels:
    - pytorch
    - conda-forge

dependencies:
    - python=3.10
    - pip=23.3.1
    - numpy=1.23.5
    - scipy=1.10.1
    - scikit-image=0.19.3
    - matplotlib=3.7.3
    - openjdk=17.0.9
    - pytorch=1.13.1 
    - h5py=3.10.0
    - dask=2023.5.0
    - pydicom=2.4.3
    - pytest=7.4.3
    - pre-commit=3.5.0
    - coverage=7.3.2
    - ipykernel
    - networkx=3.1
    - pip:
        - python-bioformats=4.0.7
        - python-javabridge=4.0.3
        - protobuf=3.20.3
        - deepcell=0.12.7
        - onnx=1.14.0
        - onnxruntime=1.15.1
        - opencv-contrib-python=4.8.1.78
        - openslide-python=1.3.1
        - scanpy=1.9.6
        - anndata=0.9.2
        - tqdm=4.66.1
        - loguru=0.7.2
        - pandas=2.0.3
        - torch-geometric=2.3.1
        - JPype1=1.4.1
        - torchvision=0.14.1
        - spams
