#!/usr/bin/env bash

# bf-unconfigured: a script for identifying datasets with no .bioformats configuration

# Required JARs: bioformats_package.jar, bio-formats-testing-framework.jar

RESOLVED_PATH=$(readlink -f "$0" 2>/dev/null \
  || perl -MCwd -le 'print Cwd::abs_path(shift)' "$0" 2>/dev/null \
  || echo "$0")
BF_DIR=$(dirname $RESOLVED_PATH)

BF_PROG=loci.tests.testng.ReportEnabledStatus "$BF_DIR/bf.sh" "$@"
