#!/usr/bin/env bash

# domainlist: a script for listing supported domains in Bio-Formats

# Required JARs: bioformats_package.jar

RESOLVED_PATH=$(readlink -f "$0" 2>/dev/null \
  || perl -MCwd -le 'print Cwd::abs_path(shift)' "$0" 2>/dev/null \
  || echo "$0")
BF_DIR=$(dirname $RESOLVED_PATH)

BF_PROG=loci.formats.tools.PrintDomains "$BF_DIR/bf.sh" "$@"
