#!/usr/bin/env bash

# showinf: a script for displaying information about a given
#          image file, while displaying it in the image viewer

# Required JARs: bioformats_package.jar

RESOLVED_PATH=$(readlink -f "$0" 2>/dev/null \
  || perl -MCwd -le 'print Cwd::abs_path(shift)' "$0" 2>/dev/null \
  || echo "$0")
BF_DIR=$(dirname $RESOLVED_PATH)

BF_PROG=loci.formats.tools.ImageInfo "$BF_DIR/bf.sh" "$@"
