name: pathml

channels:
    - conda-forge
    - pytorch

dependencies:
    - python<=3.10
    - pip==23.3.2
    - numpy==1.23.5
    - scipy<=1.11.4
    - scikit-image<=0.22.0
    - matplotlib<=3.8.2
    - openjdk<=18.0.0
    - h5py==3.10.0
    - dask<=2023.12.1
    - pydicom==2.4.4
    - pytest==7.4.3 
    - pre-commit<=3.6.0
    - coverage==7.3.4
    - networkx<=3.2.1
    - pip:
        - torch==1.13.1
        - python-bioformats==4.0.7
        - python-javabridge==4.0.3
        - protobuf==3.20.3
        - onnx==1.15.0
        - onnxruntime==1.16.3
        - opencv-contrib-python==4.8.1.78
        - openslide-python==1.3.1
        - scanpy==1.9.6
        - anndata<=0.10.3
        - tqdm==4.66.1
        - loguru==0.7.2
        - pandas<=2.1.4
        - torch-geometric==2.3.1
        - jpype1==1.4.1
